version: '3.9'

services:
  mongodb:
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    # volumes:
    #   - mongodb:/data/db


  chopper:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3001:3001"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb

# volumes:
#   - mongodb_data: {}

